### ISSUE TITLE
Releases 1.2.* are not available in bower

### ISSUE THREAD

**Issue by acuper** [timdown/rangy-release#2]
Since yesterday rangy 1.2.3 is not available in bower repo. 
We have a projects depending on this version and it would be very nice to have this version back in bower.
Otherwise we will have to start migration to 1.3 (alpha) with full testing or avoid using bower and include rangy 1.2.3 directly into the project.

**Comment by timdown** [comment]
What happened yesterday was that the owner of the `rangy` Bower package, which is not me because I was slow to get on the Bower bandwagon, unregistered the name and I registered my Rangy 1.3 package (previously available as `rangy-official`) as `rangy` instead. I hadn't realised that his was pointing to a Rangy 1.2 release. I'll sort this out later today. Apologies.

**Comment by timdown** [comment]
I've added a 1.2.3 release to the Bower package.
